[workspace]
authors = ["thomasmarwitz <thomasmarwitz3@gmail.com>"]
channels = ["conda-forge"]
name = "phase2"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."


[dependencies]
python = ">=3.9"
torchaudio = ">=2.5.1,<3"
pynput = ">=1.8.1,<2"
transformers = ">=4.51.3,<5"
portaudio = ">=19.7.0,<20"
click = ">=8.1.8,<9"


[host-dependencies]
pip = "*"
setuptools-scm = "*"
setuptools = ">=61"

[feature.dev.dependencies]
mypy = "*"
optuna = "*"
pytest = ">=6"
pytest-cov = "*"
[feature.dev.tasks]
coverage = "pytest tests --cov=campus_plan_bot --cov-report=xml --cov-report term-missing --color=yes"
test = "pytest"

[feature.lint.dependencies]
pre-commit = "*"
black = "*"
mypy = "*"
ruff = "*"
prettier = "*"
taplo = "*"
typos = "*"
docformatter = "*"
pre-commit-hooks = "*"
types-setuptools = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.build.dependencies]
python-build = "*"

[feature.build.tasks]
build = "python -m build"

[feature.py39.dependencies]
python = "3.9.*"

[environments]
default = ["dev"]
py39 = ["py39", "dev"]

lint = { features = ["lint"], no-default-feature = true }

build = ["build"]

[pypi-dependencies]
pyaudio = ">=0.2.14, <0.3"
soundfile = ">=0.13.1, <0.14"
