[workspace]
authors = ["thomasmarwitz <thomasmarwitz3@gmail.com>"]
channels = ["conda-forge"]
name = "phase2"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."


[dependencies]
python = ">=3.9"
torchaudio = ">=2.5.1,<3"
pynput = ">=1.8.1,<2"
transformers = ">=4.51.3,<5"
portaudio = ">=19.7.0,<20"
click = ">=8.1.8,<9"
huggingface_hub = ">=0.31.2,<0.32"
loguru = ">=0.7.3,<0.8"
sentence-transformers = ">=4.1.0,<5"
sseclient = ">=0.0.27,<0.0.28"
types-requests = ">=2.32.0.20250515,<3"
ffmpeg = ">=7.1.1,<8"
bert_score = ">=0.3.9,<0.4"
pydantic = ">=2.11.4,<3"
pydantic-evals = ">=0.2.14,<0.3"
plotly = ">=6.1.2,<7"
python-kaleido = ">=0.2.1,<0.3"
wordcloud = ">=1.9.4,<2"
matplotlib = ">=3.9.4,<4"
jupyter = ">=1.1.1,<2"
pandas = ">=2.3.0,<3"
geopy = ">=2.4.1,<3"
tqdm = ">=4.67.1,<5"
numpy = ">=2.0.2,<3"
anthropic = ">=0.54.0,<0.55"
llama-index = ">=0.12.25,<0.13"
rich = ">=14.0.0,<15"
einops = ">=0.8.1,<0.9"
pytest-asyncio = ">=1.0.0,<2"

[host-dependencies]
pip = "*"
setuptools-scm = "*"
setuptools = ">=61"

[feature.dev.dependencies]
mypy = "*"
optuna = "*"
pytest = ">=6"
pytest-cov = "*"
[feature.dev.tasks]
coverage = "pytest tests --cov=campus_plan_bot --cov-report=xml --cov-report term-missing --color=yes"
test = "pytest"

[feature.lint.dependencies]
pre-commit = "*"
black = "*"
mypy = "*"
ruff = "*"
prettier = "*"
taplo = "*"
typos = "*"
docformatter = "*"
pre-commit-hooks = "*"
types-setuptools = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.build.dependencies]
python-build = "*"

[feature.build.tasks]
build = "python -m build"

[feature.py39.dependencies]
python = "3.9.*"
[feature.py311.dependencies]
python = "3.11.*"

[environments]
default = ["dev"]
py311 = ["py311", "dev"]
py39 = ["py39", "dev"]

lint = { features = ["lint"], no-default-feature = true }

build = ["build"]

[pypi-dependencies]
pyaudio = ">=0.2.14, <0.3"
soundfile = ">=0.13.1, <0.14"
llama-index-embeddings-huggingface = ">=0.5.0,<0.6"
